// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3_eYU5PcH2wM2Fc4GJy1nQSTNFMh3RQw',
    appId: '1:485477654777:web:bcc4abfc38f9aec2a84228',
    messagingSenderId: '485477654777',
    projectId: 'pokedex-apiapp',
    authDomain: 'pokedex-apiapp.firebaseapp.com',
    storageBucket: 'pokedex-apiapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU-VYMsiiP66POYo9WhTRwBA-Kysqcv8g',
    appId: '1:485477654777:android:71d283786273798ea84228',
    messagingSenderId: '485477654777',
    projectId: 'pokedex-apiapp',
    storageBucket: 'pokedex-apiapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ_qVxjanI4knKfAPKC9xp2-cs_Dn1SFc',
    appId: '1:485477654777:ios:09b9e68fcf4ac66ba84228',
    messagingSenderId: '485477654777',
    projectId: 'pokedex-apiapp',
    storageBucket: 'pokedex-apiapp.appspot.com',
    iosClientId: '485477654777-6hs4i0blqto60ql3r83n4nb9r1e53n84.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ_qVxjanI4knKfAPKC9xp2-cs_Dn1SFc',
    appId: '1:485477654777:ios:09b9e68fcf4ac66ba84228',
    messagingSenderId: '485477654777',
    projectId: 'pokedex-apiapp',
    storageBucket: 'pokedex-apiapp.appspot.com',
    iosClientId: '485477654777-6hs4i0blqto60ql3r83n4nb9r1e53n84.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
